[tool.pdm]
distribution = true

[project]
name = "rest-api-stub"
version = "0.2.1"
authors = [
    {name = "NEC corporation."},
]
dependencies = [
    "uvicorn<1.0.0,>=0.30.6",
    "fastapi<1.0.0,>=0.115.0",
    "requests>=2.32.3",
    ]
requires-python = "<4.0,>=3.14"

[tool.pdm.build]
includes = []
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.isort]
profile = "black"
line_length = 120

[tool.black]
line-length = 120
